
# wqbenchdata

<!-- badges: start -->
<!-- badges: end -->

The goal of wqbenchdata is to ...

## Installation

``` r
# install.packages("remotes")
remotes::install_github("bcgov/wqbenchdata")
```

## Getting Help or Reporting an Issue

To report issues, bugs or enhancements, please file an [issue](https://github.com/bcgov/wqbenchdata/issues). 
Check out the [support](https://github.com/bcgov/wqbenchdata/blob/main/.github/SUPPORT.md) for more info. 

## Code of Conduct

Please note that the wqbench project is released with a [Contributor Code of Conduct](https://contributor-covenant.org/version/2/1/CODE_OF_CONDUCT.html). 
By contributing to this project, you agree to abide by its terms.

## License 

The code is released under the Apache License 2.0

> Copyright 2023 Province of British Columbia
> 
> Licensed under the Apache License, Version 2.0 (the "License");
> you may not use this file except in compliance with the License.
> You may obtain a copy of the License at 
> 
> https://www.apache.org/licenses/LICENSE-2.0
> 
> Unless required by applicable law or agreed to in writing, software
> distributed under the License is distributed on an "AS IS" BASIS,
> WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
> See the License for the specific language governing permissions and
> limitations under the License.

## Reference

1. Olker, J. H., Elonen, C. M., Pilli, A., Anderson, A., Kinziger, B., Erickson, S., Skopinski, M., Pomplun, A., LaLone, C. A., Russom, C. L., & Hoff, D. (2022). The ECOTOXicology Knowledgebase: A Curated Database of Ecologically Relevant Toxicity Tests to Support Environmental Research and Risk Assessment. Environmental Toxicology and Chemistry, 41(6):1520-1539. https://doi.org/10.1002/etc.5324
